### ISSUE TITLE
Build fails with go 1.12 due to `go vet -shadow` in Makefile

### ISSUE THREAD

**Issue by jamesquilty** [Brightscout/mattermost-plugin-disable-dm#3]
So, the `go` developers decided to remove the "experimental" checker shadow (see [golang/go/issue/29260](https://github.com/golang/go/issues/29260) and references therein). This means that the Makefile throws an error at line 69 where it tries to run `@$(GO) vet -shadow $(PKGS)`:

```
Running GOVET
vet: flag "-shadow" not defined
Run "go help vet" for more information
make: *** [govet] Error 2
```

Taking the brualist approach and deleting that line allowed the build to complete. It would be great if the Makefile was corrected at source, please.

**Comment by hanzei** [comment]
Downstreaming the latest makefile from https://github.com/mattermost/mattermost-plugin-sample/blob/master/Makefile will help.

**Comment by medzoom** [comment]
sorry, dont understand to downstream the makefile? in the directory of <mattermost-plugin-disable-dm> are a bunch of Makefiles? 

actually I dont have the <mattermost-plugin-sample> not installed?

best regards

**Comment by hanzei** [comment]
I'm saying that https://github.com/Brightscout/mattermost-plugin-disable-dm/blob/master/Makefile#L69 should be replaced with https://github.com/mattermost/mattermost-plugin-sample/blob/master/Makefile#L58-L59
